title_name = "Halo 3"
title_id = "4D5307E6" # MS-2022

[[patch]]
    name = "Allow public IP addresses."
    desc = "Allows the game to connect to players who are not on the current network."
    author = "craftycodie"
    is_enabled = true

    [[patch.be16]]
        address = 0x823B6FF0
        value = 0x4800

    [[patch.be32]]
        address = 0x823B7468
        value = 0x60000000

    [[patch.be32]]
        address = 0x823B6E10
        value = 0x60000000
    
    [[patch.be32]]
        address = 0x823B6D80
        value = 0x60000000

# Temp fix for service tags

[[patch]]
    name = "Disable string validation"
    desc = "Crude temporary solution"
    author = "codie"
    is_enabled = true

    [[patch.be32]]
        address = 0x826D339C
        value = 0x60000000
