title_name = "Halo 4"
title_id = "4D530919" # MS-2329
hash = "28B1F695AC7E881F" # v15.0
#media_id = "1C9D20BC" # Disc (World): http://redump.org/disc/37084

[[patch]]
    name = "Allow public IP addresses."
    desc = "Allows the game to connect to players who are not on the current network."
    author = "codie, Adrian"
    is_enabled = true

    [[patch.be32]]
        address = 0x827E6538 # transport_address_get_insecure_xbox_address
        value = 0x60000000

[[patch]]
    name = "Disable XStringVerify" # c_verify_strings_task
    author = "codie, Adrian, wild"
    is_enabled = true

    [[patch.be32]]
        address = 0x82702D80 # XStringVerify
        value = 0x60000000
