version: '3'
services:
  backend:
    build: .
    environment:
        API_PORT: 36000
        MONGO_URI: mongodb://database:27017/
        SWAGGER_API: true
    ports:
      - '36000:36000'
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - './data/mongo:/data/db'
