name: CI

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'appveyor.yml'
      - 'hero.jpg'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'appveyor.yml'
      - 'hero.jpg'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: npm install
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: Xenia-WebServices
          path: dist
          if-no-files-found: error
